# Generated by Django 4.0.2 on 2022-02-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'Ropa'},
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ropa/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cigarro', 'cigarro'), ('comida', 'comida'), ('bebida', 'bebida'), ('cafe', 'cafe'), ('aseo', 'aseo'), ('otro', 'otro')], max_length=50, verbose_name='Tipo')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de comprado')),
                ('description', models.CharField(blank=True, max_length=222, null=True, verbose_name='Decripcion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['date_creation'],
            },
        ),
    ]
