# Generated by Django 4.0.2 on 2022-02-28 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0003_alter_clothing_options_product_cost_product_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantify',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Costo USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Descripción'),
        ),
    ]
