# Generated by Django 4.0.2 on 2022-03-01 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('p_price', models.DecimalField(decimal_places=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Costo CUP')),
                ('s_price', models.DecimalField(decimal_places=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Precio CUP')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('High', 'Alta'), ('Normal', 'Normal'), ('Low', 'Baja')], default='Low', max_length=22, verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta disponible')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.prodcategory', verbose_name='Categoría')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['cat', 'name'],
            },
        ),
    ]
