# Generated by Django 4.0.2 on 2022-03-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Número del celular', max_length=30, verbose_name='Celular'),
        ),
    ]
