# Generated by Django 4.0.2 on 2022-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_alter_client_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
        migrations.AddField(
            model_name='client',
            name='debt',
            field=models.ManyToManyField(blank=True, null=True, to='debt.Debt', verbose_name='Deuda'),
        ),
    ]
