# Generated by Django 4.0.2 on 2022-03-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_remove_client_debt_client_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
        migrations.AddField(
            model_name='debt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.client', verbose_name='Cliente'),
        ),
    ]
