# Generated by Django 4.0.2 on 2022-03-01 03:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantify', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Cantidad')),
                ('date_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('date_to_pay', models.DateField(blank=True, null=True, verbose_name='Dia a pagar')),
                ('description', models.CharField(max_length=222, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Deuda',
                'ordering': ['date_creation', 'quantify'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Número del celular', max_length=31, verbose_name='Celular')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt.debt', verbose_name='Deuda')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['name'],
            },
        ),
    ]
