# Generated by Django 4.0.2 on 2022-03-01 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0005_remove_client_debt_debt_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['client', 'date_creation', 'quantify'], 'verbose_name': 'Deuda'},
        ),
        migrations.AlterField(
            model_name='debt',
            name='quantify',
            field=models.DecimalField(decimal_places=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0, message='Escriba un numero positivo')], verbose_name='Cantidad'),
        ),
    ]
